@api = http://localhost:3000/vehicles

GET {{api}}

###
POST {{api}}
Content-Type:  application/json

{ 
    "tipo_vehiculo": "carrazo",
    "placa": "LAM345",
    "tarifa": "200"
}

{ 
    "tipo_vehiculo": "motaza",
    "placa": "MOT345",
    "tarifa": "200"
}